# syntax=docker/dockerfile:1.4
FROM debian:bookworm-slim

RUN \
    apt-get update && \
    apt-get -y install --no-install-recommends nginx && \
    rm -rf /var/lib/apt/lists/*

ARG GIT_HASH=unknown
ARG GIT_SHORT_HASH=unknown
ARG GIT_BRANCH=main
ENV GIT_HASH=${GIT_HASH}
ENV GIT_SHORT_HASH=${GIT_SHORT_HASH}
ENV GIT_BRANCH=${GIT_BRANCH}

COPY docker/nginx/nginx.production.conf /etc/nginx/sites-enabled/
RUN rm -f /etc/nginx/sites-enabled/default

CMD ["nginx", "-g", "daemon off;"]
